# Exploring Stock Data using brapi-dev api

## Load ingested data into spark tables

In [1]:
from spark import loader

spark = loader.create_spark_session("brapi-api")

loader.load_spark_tables(spark)

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/06/06 17:08:08 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
26/06/06 17:08:11 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

## Exploring the catalog

In [25]:
for table in spark.catalog.listTables():
    df = spark.table(table.name).toPandas()  # pandas usage for better data display instead of pure text on native spark
    print(f"---- {table.name} ----\n")
    display(df.head(5))
    print("\n")

---- activetickers ----

,change,close,logo,market_cap,name,sector,stock,subType,type,volume
0,-1.84,19.17,https://icons.brapi.dev/icons/BBAS3.svg,1.116885e+11,BCO BRASIL S.A.,Finance,BBAS3,stock,stock,51043500
1,0.28,3.59,https://icons.brapi.dev/icons/CSAN3.svg,1.417206e+10,COSAN S.A.,Utilities,CSAN3,stock,stock,40491100
2,0.28,38.83,https://icons.brapi.dev/icons/ITUB4.svg,4.326504e+11,ITAU UNIBANCO HOLDING S.A.,Finance,ITUB4,stock,stock,34701800
3,-0.87,40.89,https://icons.brapi.dev/icons/PETR4.svg,5.610603e+11,PETROLEO BRASILEIRO S.A. PETROBRAS,Energy Minerals,PETR4,stock,stock,34533700
4,-10.18,6.00,https://icons.brapi.dev/icons/CSNA3.svg,8.808812e+09,CIA SIDERURGICA NACIONAL,Non-Energy Minerals,CSNA3,stock,stock,34491000

---- balancesheethistoryquarterly ----

,stock,type,endDate,cash,shortTermInvestments,netReceivables,inventory,otherCurrentAssets,totalCurrentAssets,longTermInvestments,...,longTermDebitsFromOperations,longTermTechnicalProvisions,longTermInsuranceAndReinsurance,longTermComplementaryPension,longTermCapitalization,otherLongTermProvisions,debitsFromCapitalization,debitsFromOtherOperations,otherProvisions,advanceForFutureCapitalIncrease
0,PETR4,quarterly,2026-03-31,34294000000,1.330600e+10,2.224000e+10,4.855600e+10,1.137100e+10,1.405330e+11,3.091000e+09,...,None,None,None,None,None,None,None,None,None,None
1,PETR4,quarterly,2025-12-31,35608000000,1.500000e+10,2.546100e+10,4.517300e+10,7.637000e+09,1.400260e+11,3.024000e+09,...,None,None,None,None,None,None,None,None,None,None
2,PETR4,quarterly,2025-09-30,47675000000,1.432600e+10,2.189100e+10,4.627200e+10,8.953000e+09,1.493610e+11,4.225000e+09,...,None,None,None,None,None,None,None,None,None,None
3,PETR4,quarterly,2025-06-30,38177000000,1.367000e+10,1.847400e+10,4.492700e+10,1.055600e+10,1.358590e+11,4.243000e+09,...,None,None,None,None,None,None,None,None,None,None
4,PETR4,quarterly,2025-03-31,26959999000,1.707800e+10,1.762300e+10,4.277900e+10,1.108300e+10,1.248530e+11,4.178000e+09,...,None,None,None,None,None,None,None,None,None,None

---- cashflowhistoryquarterly ----

,stock,type,endDate,operatingCashFlow,incomeFromOperations,netIncomeBeforeTaxes,adjustmentsToProfitOrLoss,changesInAssetsAndLiabilities,otherOperatingActivities,cashGeneratedInOperations,investmentCashFlow,financingCashFlow,exchangeVariationWithoutCash,foreignExchangeRateWithoutCash,increaseOrDecreaseInCash,initialCashBalance,finalCashBalance,freeCashFlow
0,PETR4,quarterly,2026-03-31,43975000000,63286000000,NaN,NaN,-9.826000e+09,-9.485000e+09,None,-18812000000,-24953000000,NaN,-1.524000e+09,-1314000000,3.560800e+10,3.429400e+10,2.516300e+10
1,PETR4,quarterly,2025-12-31,54916000000,60572000000,NaN,NaN,NaN,NaN,None,-35377000000,-32590000000,NaN,NaN,-12067000000,NaN,NaN,NaN
2,PETR4,quarterly,2025-09-30,53655000000,68532000000,NaN,NaN,-1.009900e+10,-4.778000e+09,None,-25937000000,-17595000000,NaN,-6.250000e+08,9498000000,0.000000e+00,9.498000e+09,2.771800e+10
3,PETR4,quarterly,2025-06-30,42424000000,59311000000,NaN,NaN,-1.054400e+10,-6.343000e+09,None,-14565000000,-15493000000,NaN,-1.149000e+09,11217000000,0.000000e+00,1.121700e+10,2.785900e+10
4,PETR4,quarterly,2025-03-31,49338000000,65560000000,NaN,NaN,-6.436000e+09,-9.786000e+09,None,-10235000000,-31444000000,NaN,-9.530000e+08,6706000000,2.025400e+10,2.696000e+10,3.910300e+10

---- defaultkeystatistics ----

,currency,defaultKeyStatistics,earningsPerShare,fiftyTwoWeekHigh,fiftyTwoWeekLow,fiftyTwoWeekRange,logourl,longName,marketCap,priceEarnings,...,regularMarketDayHigh,regularMarketDayLow,regularMarketDayRange,regularMarketOpen,regularMarketPreviousClose,regularMarketPrice,regularMarketTime,regularMarketVolume,shortName,symbol
0,BRL,"(0.45961496, None, None, None, 0.37789977, Non...",8.347058,50.690000,28.860000,28.86 - 50.69,https://icons.brapi.dev/icons/PETR4.svg,Petroleo Brasileiro SA Pfd,561060286488,4.898707,...,41.43,40.65,40.65 - 41.43,41.03,40.84,40.89,2026-06-05T21:30:30.000Z,34533700,PETR4,PETR4
1,BRL,"(-0.3861489, None, None, None, 1.9457138, None...",0.176378,11.552381,5.290000,5.29 - 11.55238092,https://icons.brapi.dev/icons/MGLU3.svg,Magazine Luiza S.A.,3763956340,32.000000,...,5.67,5.29,5.29 - 5.67,5.44,5.44,5.44,2026-06-05T21:30:30.000Z,27749100,MGLU3,MGLU3
2,BRL,"(0.7089251, None, None, None, 0.7362207, None,...",3.655242,91.620000,49.720000,49.72 - 91.62,https://icons.brapi.dev/icons/VALE3.svg,Vale S.A.,340976883748,21.602481,...,80.79,78.33,78.33 - 80.79,80.79,78.55,78.70,2026-06-05T21:30:30.000Z,22910600,VALE3,VALE3
3,BRL,"(0.16361457, None, None, None, 1.1103773, None...",4.158373,49.670000,33.187561,33.18756079 - 49.67,https://icons.brapi.dev/icons/ITUB4.svg,Itau Unibanco Holding SA Pfd,432650440829,9.783814,...,39.17,38.57,38.57 - 39.17,38.75,39.04,38.83,2026-06-05T21:30:30.000Z,34701800,ITUB4,ITUB4

---- defaultkeystatisticshistoryquarterly ----

,stock,type,endDate,price,enterpriseValue,forwardPE,profitMargins,sharesOutstanding,bookValue,priceToBook,...,pegRatio,enterpriseToRevenue,enterpriseToEbitda,lastDividendValue,lastDividendDate,marketCap,trailingPE,dividendYield,yield,earningsPerShare
0,PETR4,quarterly,2026-03-31,41.249996,1.161037e+12,None,0.216898,12888733000,34.540943,1.194235,...,0.04524,2.330974,5.028660,None,None,5.316602e+11,5.504934,0.07,0.07,8.347058
1,PETR4,quarterly,2025-12-31,45.470002,1.210130e+12,None,0.222300,12888733000,32.399384,1.403422,...,0.02927,2.432182,5.261067,None,None,5.860507e+11,5.878908,0.06,0.06,8.581526
2,PETR4,quarterly,2025-09-30,30.311695,9.976043e+11,None,0.158695,12888733000,32.971510,0.919330,...,NaN,2.029937,4.747965,None,None,3.906793e+11,5.390962,0.16,0.16,6.051022
3,PETR4,quarterly,2025-06-30,29.567039,9.872606e+11,None,0.157809,12888733000,31.173119,0.948479,...,NaN,2.002062,4.767280,None,None,3.810816e+11,5.340665,0.18,0.18,6.037754
4,PETR4,quarterly,2025-03-31,33.564720,1.031483e+12,None,0.097793,12888733000,30.848883,1.088037,...,NaN,2.078546,5.017549,None,None,4.326067e+11,9.855353,0.19,0.19,3.765304

---- financialdatahistoryquarterly ----

,stock,type,endDate,currentPrice,totalCash,totalCashPerShare,ebitda,totalDebt,quickRatio,currentRatio,...,operatingCashflow,earningsGrowth,revenueGrowth,earningsGrowthAnnual,revenueGrowthAnnual,grossMargins,ebitdaMargins,operatingMargins,profitMargins,financialCurrency
0,PETR4,quarterly,2026-03-31,None,4.760000e+10,3.693148,2.308840e+11,6.769770e+11,0.486224,0.742908,...,1.949700e+11,1.216835,0.003706,2.008496,0.013691,0.473590,0.463538,0.288819,0.216898,None
1,PETR4,quarterly,2025-12-31,None,5.060800e+10,3.926530,2.300160e+11,6.746870e+11,0.478167,0.705890,...,2.003330e+11,2.008496,0.013691,2.008496,0.013691,0.476331,0.462298,0.292691,0.222300,None
2,PETR4,quarterly,2025-09-30,None,6.200100e+10,4.810481,2.101120e+11,6.689260e+11,0.565283,0.819013,...,1.930830e+11,-0.084671,-0.024558,-0.706226,-0.041338,0.481520,0.427538,0.265160,0.158695,None
3,PETR4,quarterly,2025-06-30,None,5.184700e+10,4.022661,2.070910e+11,6.580260e+11,0.507490,0.758226,...,2.021480e+11,-0.017661,-0.011908,-0.706226,-0.041338,0.490958,0.419959,0.269992,0.157809,None
4,PETR4,quarterly,2025-03-31,None,4.403800e+10,3.416783,2.055750e+11,6.429140e+11,0.472156,0.718256,...,2.068940e+11,-0.563187,0.011424,-0.706226,-0.041338,0.496663,0.414255,0.274486,0.097793,None

---- incomestatementhistoryquarterly ----

,stock,type,endDate,totalRevenue,costOfRevenue,grossProfit,researchDevelopment,sellingGeneralAdministrative,nonRecurring,otherOperatingExpenses,...,basicEarningsPerShare,dilutedEarningsPerShare,insuranceOperations,reinsuranceOperations,complementaryPensionOperations,capitalizationOperations,cleanEbit,cleanEbitda,cleanNopat,cleanNetIncome
0,PETR4,quarterly,2026-03-31,123686000000,-64084000000,59602000000,None,-2.517000e+09,None,-7.899000e+09,...,None,None,None,None,None,None,4.127000e+10,4.127000e+10,2.723820e+10,None
1,PETR4,quarterly,2025-12-31,127371000000,-68878000000,58493000000,None,-2.854000e+09,None,-1.808900e+10,...,None,None,None,None,None,None,2.848500e+10,2.848500e+10,1.880010e+10,None
2,PETR4,quarterly,2025-09-30,127906000000,-66789000000,61117000000,None,-2.729000e+09,None,-7.532000e+09,...,None,None,None,None,None,None,4.363500e+10,4.363500e+10,2.879910e+10,None
3,PETR4,quarterly,2025-06-30,119128000000,-62449000000,56679000000,None,-2.627000e+09,None,-1.655500e+10,...,None,None,None,None,None,None,3.046800e+10,3.046800e+10,2.010888e+10,None
4,PETR4,quarterly,2025-03-31,123144000000,-62435000000,60709000000,None,-2.592000e+09,None,-9.196000e+09,...,None,None,None,None,None,None,4.304000e+10,4.304000e+10,2.840640e+10,None

---- valueaddedhistoryquarterly ----

,stock,type,endDate,revenue,productSales,otherRevenues,constructionOfOwnAssets,provisionOrReversalOfDoubtfulAccounts,suppliesPurchasedFromThirdParties,costsWithProductsSold,...,feesRevenue,variationsOfTechnicalProvisions,insuranceOperationsVariations,pensionOperationsVariations,otherVariations,netOperatingRevenue,claimsAndBenefits,variationInDeferredSellingExpenses,resultsOfCededReinsuranceOperations,resultOfCoinsuranceOperationsAssigned
0,PETR4,quarterly,2026-03-31,191003000000,1.594970e+11,7693000000,2.377000e+10,43000000.0,-66740000000,-2.096200e+10,...,None,None,None,None,None,None,None,None,None,None
1,PETR4,quarterly,2025-12-31,194300000000,1.648460e+11,4038000100,2.564200e+10,-226000000.0,-83922000000,-2.544700e+10,...,None,None,None,None,None,None,None,None,None,None
2,PETR4,quarterly,2025-09-30,197877000000,1.655260e+11,4639000000,2.772300e+10,-11000000.0,-73790000000,-2.513200e+10,...,None,None,None,None,None,None,None,None,None,None
3,PETR4,quarterly,2025-06-30,177556000000,1.541870e+11,2732000000,2.095200e+10,-315000000.0,-70741000000,-2.352500e+10,...,None,None,None,None,None,None,None,None,None,None
4,PETR4,quarterly,2025-03-31,179824000000,1.572590e+11,3283000000,1.917000e+10,112000000.0,-63757000000,-2.314900e+10,...,None,None,None,None,None,None,None,None,None,None